// Copyright (c) 2017 ChromaWay Inc. See README for license information.

/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "Messages"
 */
package net.postchain.gtv.messages;

import java.io.*;
import java.util.*;

import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;

public class Gtv {

	public static final int null_Chosen = 0;
	public static final int byteArrayChosen = 1;
	public static final int stringChosen = 2;
	public static final int integerChosen = 3;
	public static final int dictChosen = 4;
	public static final int arrayChosen = 5;

	public final int choiceID;

	@Alternative(0)
	public final Object null_;

	@Alternative(1)
	public final byte[] byteArray;

	@Alternative(2)
	public final String string;

	@Alternative(3)
	public final Long integer;

	@Alternative(4)
	public final Vector<DictPair> dict;

	@Alternative(5)
	public final Vector<Gtv> array;


	private Gtv(int choiceID, Object null_, byte[] byteArray, String string, Long integer, Vector<DictPair> dict, Vector<Gtv> array) {
		this.choiceID = choiceID;
		this.null_ = null_;
		this.byteArray = byteArray;
		this.string = string;
		this.integer = integer;
		this.dict = dict;
		this.array = array;
	}

	public static Gtv null_(Object null_) {
		return new Gtv(null_Chosen, null_, null, null, null, null, null);
	}

	public static Gtv byteArray(byte[] byteArray) {
		return new Gtv(byteArrayChosen, null, byteArray, null, null, null, null);
	}

	public static Gtv string(String string) {
		return new Gtv(stringChosen, null, null, string, null, null, null);
	}

	public static Gtv integer(Long integer) {
		return new Gtv(integerChosen, null, null, null, integer, null, null);
	}

	public static Gtv dict(Vector<DictPair> dict) {
		return new Gtv(dictChosen, null, null, null, null, dict, null);
	}

	public static Gtv array(Vector<Gtv> array) {
		return new Gtv(arrayChosen, null, null, null, null, null, array);
	}

	public boolean equals(Object obj) {
		if(!(obj instanceof Gtv)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static Gtv der_decode(InputStream in) throws IOException {
		return (Gtv)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Messages.type(65538);

	public final static ChoiceConverter CONV;

	static {
		CONV = new AnnotationChoiceConverter(Gtv.class);
		AsnConverter null_Converter = NullConverter.INSTANCE;
		AsnConverter byteArrayConverter = OctetStringConverter.INSTANCE;
		AsnConverter stringConverter = StringConverter.INSTANCE;
		AsnConverter integerConverter = LongConverter.INSTANCE;
		AsnConverter dictConverter = new VectorConverter(DictPair.CONV);
		AsnConverter arrayConverter = new VectorConverter(Gtv.CONV);
		CONV.setAlternativeConverters(new AsnConverter[] { null_Converter, byteArrayConverter, stringConverter, integerConverter, dictConverter, arrayConverter });
	}


}
